<a href="https://colab.research.google.com/github/Ronaldo07-08/ML_Prac/blob/main/IvanovHw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#!pip install -r requirements.txt

In [ ]:
import torch
import math
import time

# Задание 1: Создание и манипуляции с тензорами


*1.1 Создание тензоров*

In [ ]:

def create_tensors() -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
    """
    Создает и возвращает базовые тензоры

    Returns:
        tuple: Кортеж из четырех тензоров (random_tensor, zeros_tensor, ones_tensor, range_tensor).
    """

    # 1. Тензор размером 3x4, заполненный случайными числами от 0 до 1
    random_tensor = torch.rand(3, 4)

    # 2. Тензор размером 2x3x4, заполненный нулями
    zeros_tensor = torch.zeros(2, 3, 4)

    # 3. Тензор размером 5x5, заполненный единицами
    ones_tensor = torch.ones(5, 5)

    # 4. Тензор размером 4x4 с числами от 0 до 15
    range_tensor = torch.arange(16).reshape(4, 4)

    return random_tensor, zeros_tensor, ones_tensor, range_tensor

try:
    t_rand, t_zeros, t_ones, t_range = create_tensors()

    print("Случайный тензор 3x4:\n", t_rand, "\nРазмер:", t_rand.shape, "\n")
    print("Тензор нулей 2x3x4:\n", t_zeros, "\nРазмер:", t_zeros.shape, "\n")
    print("Тензор единиц 5x5:\n", t_ones, "\nРазмер:", t_ones.shape, "\n")
    print("Тензор 0-15 4x4:\n", t_range, "\nРазмер:", t_range.shape)

except Exception as e:
    print(f"Ошибка при создании тензоров: {e}")

Случайный тензор 3x4:
 tensor([[0.7742, 0.0652, 0.0922, 0.1792],
        [0.9622, 0.2483, 0.4142, 0.4646],
        [0.1476, 0.4993, 0.0172, 0.1571]]) 
Размер: torch.Size([3, 4]) 

Тензор нулей 2x3x4:
 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]) 
Размер: torch.Size([2, 3, 4]) 

Тензор единиц 5x5:
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) 
Размер: torch.Size([5, 5]) 

Тензор 0-15 4x4:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]) 
Размер: torch.Size([4, 4])


*1.2 Операции с тензорами*

In [ ]:

def task_1_2_operations() -> None:
    """
    Выполняет базовые операции с тензорами.
    Включает транспонирование, матричное и поэлементное умножение.
    """

    A = torch.rand(3, 4)
    B = torch.rand(4, 3)

    # Проверка размерностей перед операциями
    assert A.shape == (3, 4), "Тензор A должен быть 3x4"
    assert B.shape == (4, 3), "Тензор B должен быть 4x3"

    # 1. Транспонирование тензора A
    A_transposed = A.T

    # 2. (3x4 @ 4x3 = 3x3)
    matrix_mult = torch.matmul(A, B)

    # 3. Поэлементное умножение A и транспонированного B
    elementwise_mult = A * B.T

    # 4. Сумма всех элементов тензора A
    total_sum = A.sum()

    print(f"Размер A: {A.shape}, Размер B: {B.shape}")
    print(f"Размер транспонированного A: {A_transposed.shape}")
    print(f"Результат матричного умножения (A @ B): \n{matrix_mult}")
    print(f"Сумма всех элементов A: {total_sum.item():.4f}\n")

task_1_2_operations()

Размер A: torch.Size([3, 4]), Размер B: torch.Size([4, 3])
Размер транспонированного A: torch.Size([4, 3])
Результат матричного умножения (A @ B): 
tensor([[0.8090, 1.2776, 1.5866],
        [0.8753, 1.4565, 1.3640],
        [1.0721, 1.4116, 1.4811]])
Сумма всех элементов A: 7.1938



*1.3 Индексация и срезы*

In [ ]:
def task_1_3_slicing() -> None:
    """
    Демонстрирует работу со срезами в 3D-тензоре.
    """

    # Создаем тензор 5x5x5.
    C = torch.arange(125).reshape(5, 5, 5)

    # Возьмем первую строку самой первой матрицы
    first_row = C[0, 0, :]

    # Возьмем последний столбец первой матрицы
    last_col = C[0, :, -1]


    # Берем центральную матрицу в глубине, и срезы 1:3 по строкам и столбцам.
    center_2x2 = C[2, 1:3, 1:3]

    # Все элементы с четными индексами
    even_elements = C[::2, ::2, ::2]

    print(f"Первая строка: {first_row}")
    print(f"Последний столбец: {last_col}")
    print(f"Центральная матрица 2x2:\n{center_2x2}")
    print(f"Форма тензора с четными индексами: {even_elements.shape}\n")

task_1_3_slicing()

Первая строка: tensor([0, 1, 2, 3, 4])
Последний столбец: tensor([ 4,  9, 14, 19, 24])
Центральная матрица 2x2:
tensor([[56, 57],
        [61, 62]])
Форма тензора с четными индексами: torch.Size([3, 3, 3])



*1.4 Работа с формами*

In [ ]:
def task_1_4_shapes() -> None:
    """
    Изменяет форму (shape) тензора без изменения самих данных.
    """

    # Создаем плоский тензор на 24 элемента
    D = torch.arange(24)

    # произведение всех размерностей должно равняться исходному количеству элементов

    shape_2x12 = D.reshape(2, 12)
    shape_3x8 = D.reshape(3, 8)
    shape_4x6 = D.reshape(4, 6)

    # Переход в 3D - 2 матрицы размером 3x4
    shape_2x3x4 = D.reshape(2, 3, 4)

    # Переход в 4D
    shape_2x2x2x3 = D.reshape(2, 2, 2, 3)

    print(f"Исходный тензор: {D} \n")
    print(f"2x12: {shape_2x12} \n")
    print(f"3x8: {shape_3x8} \n")
    print(f"4x6: {shape_4x6} \n")
    print(f"2x3x4: {shape_2x3x4} \n")
    print(f"2x2x2x3: {shape_2x2x2x3} \n")

task_1_4_shapes()

Исходный тензор: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23]) 

2x12: tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]]) 

3x8: tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]]) 

4x6: tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]) 

2x3x4: tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]) 

2x2x2x3: tensor([[[[ 0,  1,  2],
          [ 3,  4,  5]],

         [[ 6,  7,  8],
          [ 9, 10, 11]]],


        [[[12, 13, 14],
          [15, 16, 17]],

         [[18, 19, 20],
          [21, 22, 23]]]]) 



# Задание 2: Автоматическое дифференцирование

*2.1 Простые вычисления с градиентами*

In [ ]:
def task_2_1_simple_gradients() -> None:
    """
    Вычисляет градиенты для функции f(x,y,z) = x^2 + y^2 + z^2 + 2*x*y*z.
    Включает аналитическую проверку.
    """

    # Задаем произвольные начальные значения
    x = torch.tensor(2.0, requires_grad=True)
    y = torch.tensor(3.0, requires_grad=True)
    z = torch.tensor(4.0, requires_grad=True)

    f = x**2 + y**2 + z**2 + 2*x*y*z
    f.backward()

    # Аналитическая проверка:
    # df/dx = 2x + 2yz = 2(2) + 2(3)(4) = 4 + 24 = 28
    # df/dy = 2y + 2xz = 2(3) + 2(2)(4) = 6 + 16 = 22
    # df/dz = 2z + 2xy = 2(4) + 2(2)(3) = 8 + 12 = 20

    print(f"PyTorch grad x: {x.grad.item():.1f} | Аналитически: 28.0")
    print(f"PyTorch grad y: {y.grad.item():.1f} | Аналитически: 22.0")
    print(f"PyTorch grad z: {z.grad.item():.1f} | Аналитически: 20.0\n")
task_2_1_simple_gradients()

PyTorch grad x: 28.0 | Аналитически: 28.0
PyTorch grad y: 22.0 | Аналитически: 22.0
PyTorch grad z: 20.0 | Аналитически: 20.0



*2.2 Градиент функции потерь*

In [ ]:
def task_2_2_mse_gradient() -> None:
    """
    Вычисляет градиенты функции потерь MSE по параметрам w и b.
    """

    x = torch.tensor([1.0, 2.0, 3.0])      # Входные данные
    y_true = torch.tensor([2.0, 4.0, 6.0]) # Целевые ответы

    w = torch.tensor(1.0, requires_grad=True) # Исходный вес
    b = torch.tensor(0.0, requires_grad=True) # Исходное смещение

    y_pred = w * x + b
    mse = ((y_pred - y_true)**2).mean()
    mse.backward()

    print(f"Ошибка (MSE): {mse.item():.4f}")
    print(f"Градиент по весу (w.grad): {w.grad.item():.4f}")
    print(f"Градиент по смещению (b.grad): {b.grad.item():.4f}\n")
task_2_2_mse_gradient()

Ошибка (MSE): 4.6667
Градиент по весу (w.grad): -9.3333
Градиент по смещению (b.grad): -4.0000



*2.3 Цепное правило*

In [ ]:
def task_2_3_chain_rule() -> None:
    """
    Проверяет цепное правило для сложной функции f(x) = sin(x^2 + 1).
    Использует torch.autograd.grad для прямого вычисления.
    """

    x = torch.tensor(2.0, requires_grad=True)
    f = torch.sin(x**2 + 1)

    grad_f = torch.autograd.grad(f, x)[0]

    # Аналитическая проверка: df/dx = cos(x^2 + 1) * 2x
    analytical_grad = torch.cos(x**2 + 1) * (2 * x)

    print(f"Autograd df/dx: {grad_f.item():.4f}")
    print(f"Аналитически:   {analytical_grad.item():.4f}\n")
task_2_3_chain_rule()

Autograd df/dx: 1.1346
Аналитически:   1.1346



# Задание 3: Сравнение производительности CPU vs CUDA

3.1 Подготовка данных

In [ ]:

shapes = [
    (64, 1024, 1024),
    (128, 512, 512),
    (256, 256, 256)
]

# Ключ - размер матрицы, значение - кортеж из двух матриц (A, B)
data_dict = {}

for shape in shapes:
    print(f"Генерация матриц размером {shape}...")
    A = torch.randn(*shape)
    B = torch.randn(*shape)
    data_dict[shape] = (A, B)


Генерация матриц размером (64, 1024, 1024)...
Генерация матриц размером (128, 512, 512)...
Генерация матриц размером (256, 256, 256)...


3.2 Функция измерения времени

In [ ]:
def measure_time(func, *args, is_gpu=False, **kwargs) -> float:
    """
    Измеряет время выполнения операций.
    Использует torch.cuda.Event() для точного измерения на GPU
    и time.time() для измерения на CPU.
    """
    if is_gpu and torch.cuda.is_available():
        start = torch.cuda.Event(enable_timing=True)
        end = torch.cuda.Event(enable_timing=True)

        start.record()
        result = func(*args, **kwargs)
        end.record()

        # Обязательная синхронизация для GPU
        torch.cuda.synchronize()
        return start.elapsed_time(end)
    else:
        start_time = time.time()
        result = func(*args, **kwargs)
        return (time.time() - start_time) * 1000 # Секунды в миллисекунды

*3.3 Сравнение операций*

In [ ]:
has_gpu = torch.cuda.is_available()
print(f"Доступен ли GPU: {'Да' if has_gpu else 'Нет (Включите T4 GPU в Среде выполнения Colab)'}\n")

# Список операций для тестирования
operations = [
    ("Матричное умножение", lambda A, B: torch.matmul(A, B)),
    ("Сложение", lambda A, B: A + B),
    ("Умножение", lambda A, B: A * B),
    ("Транспонирование", lambda A, B: A.transpose(1, 2)),
    ("Сумма элементов", lambda A, B: A.sum())
]

for shape, (A_cpu, B_cpu) in data_dict.items():
    print(f"=== Тестирование размера: {shape} ===")

    # Если есть GPU, загружаем данные в видеопамять
    if has_gpu:
        A_gpu = A_cpu.cuda()
        B_gpu = B_cpu.cuda()

    print(f"{'Операция':<22} | {'CPU (мс)':<10} | {'GPU (мс)':<10} | {'Ускорение'}")
    print("-" * 64)

    for name, op in operations:
        # 1. Измеряем время на CPU
        cpu_time = measure_time(op, A_cpu, B_cpu, is_gpu=False)

        # 2. Измеряем время на GPU (если доступен)
        if has_gpu:
            # Делаем холостой запуск для инициализации ядер CUDA
            _ = op(A_gpu, B_gpu)

            gpu_time = measure_time(op, A_gpu, B_gpu, is_gpu=True)

            # 3. Вычисляем ускорение
            speedup = cpu_time / gpu_time if gpu_time > 0 else 0

            # 4. Выводим результаты
            print(f"{name:<22} | {cpu_time:<10.2f} | {gpu_time:<10.2f} | {speedup:.1f}x")
        else:
            print(f"{name:<22} | {cpu_time:<10.2f} | {'N/A':<10} | N/A")

    # Освобождаем видеопамять перед следующим размером матриц
    if has_gpu:
        del A_gpu, B_gpu
        torch.cuda.empty_cache()

    print("\n")

Доступен ли GPU: Да

=== Тестирование размера: (64, 1024, 1024) ===
Операция               | CPU (мс)   | GPU (мс)   | Ускорение
----------------------------------------------------------------
Матричное умножение    | 1253.71    | 34.85      | 36.0x
Сложение               | 149.58     | 3.27       | 45.8x
Умножение              | 164.95     | 3.27       | 50.5x
Транспонирование       | 0.42       | 0.02       | 19.2x
Сумма элементов        | 21.80      | 0.99       | 22.0x


=== Тестирование размера: (128, 512, 512) ===
Операция               | CPU (мс)   | GPU (мс)   | Ускорение
----------------------------------------------------------------
Матричное умножение    | 554.72     | 12.04      | 46.1x
Сложение               | 112.85     | 1.64       | 68.8x
Умножение              | 232.38     | 1.64       | 141.8x
Транспонирование       | 0.04       | 0.03       | 1.1x
Сумма элементов        | 11.57      | 0.53       | 21.7x


=== Тестирование размера: (256, 256, 256) ===
Операция      

*3.4 Анализ результатов*



1.   1 - Сложение и Умножение — ускорение в 40-50 раз на всех размерах матриц.
2 - Матричное умножение: прирост производительности от 25 до 40 раз. Получается, что наибольшее ускорение получают однотипные независимые операции, их можно производить параллельно на ядрах GPU.

2.   Время, которое центральный процессор тратит на то, чтобы отправить видеокарте команду начать работу, оказывается больше, чем само время выполнения этой простейшей задачи на CPU.

3. При уменьшении общего объема элементов преимущество GPU стремительно падает. На малых данных накладные расходы съедают всю пользу от видеокарты. Для тяжелых операций ускорение большое.

4. `.cuda()` инициирует физическое копирование данных из RAM в VRAM.Копирование данных происходит очень медленно по меркам вычислений.Данные нужно загрузить на GPU один раз, провести все математические операции и только финальный результат вернуть обратно на CPU.

